// Self-learning weight transfer and auto-rig system for Metin2.
// Learns from 00-BONES 3ds Max presets, real GR2 files, and user corrections.
// Provides character-type-aware weight transfer, auto-rigging, and bone mapping.

#include "m2rig/self_learning.hpp"

#include <algorithm>
#include <cmath>
#include <fstream>
#include <iostream>
#include <limits>
#include <numeric>
#include <random>

#include "m2rig/logging.hpp"
#include "m2rig/skin_weights.hpp"
#include "m2rig/validation.hpp"

namespace m2rig {

// --- SelfLearningDatabase implementation ---

SelfLearningDatabase::SelfLearningDatabase() = default;

SelfLearningDatabase::~SelfLearningDatabase() = default;

ResultVoid SelfLearningDatabase::load(const std::filesystem::path& path) {
    dbPath_ = path;
    if (!std::filesystem::exists(path)) {
        return ResultVoid::ok(); // Empty database is valid
    }
    
    std::ifstream file(path, std::ios::binary);
    if (!file) {
        return ResultVoid::fail("Cannot open learning database: " + path.string(), "SELF_LEARN");
    }
    
    // Simple text-based format for now
    std::string line;
    LearningEntry* currentEntry = nullptr;
    
    while (std::getline(file, line)) {
        if (line.empty() || line[0] == '#') continue;
        
        if (line.rfind("ENTRY:", 0) == 0) {
            std::string key = line.substr(6);
            currentEntry = getOrCreateEntryByKey(key);
        } else if (currentEntry && line.rfind("BONEMAP:", 0) == 0) {
            // Format: BONEMAP:source->target:confidence
            std::string rest = line.substr(8);
            size_t arrow = rest.find("->");
            size_t colon = rest.rfind(':');
            if (arrow != std::string::npos && colon != std::string::npos && colon > arrow) {
                std::string src = rest.substr(0, arrow);
                std::string tgt = rest.substr(arrow + 2, colon - arrow - 2);
                float conf = std::stof(rest.substr(colon + 1));
                currentEntry->boneMap[src] = tgt;
                currentEntry->boneConfidence[src] = conf;
            }
        } else if (currentEntry && line.rfind("PATTERN:", 0) == 0) {
            // Format: PATTERN:sourceBone:targetBone:avgDist:successRate:sampleCount
            std::string rest = line.substr(8);
            std::vector<std::string> parts;
            size_t start = 0;
            while (start < rest.size()) {
                size_t pos = rest.find(':', start);
                if (pos == std::string::npos) pos = rest.size();
                parts.push_back(rest.substr(start, pos - start));
                if (pos == rest.size()) break;
                start = pos + 1;
            }
            if (parts.size() >= 5) {
                LearningEntry::TransferPattern p;
                p.sourceBone = parts[0];
                p.targetBone = parts[1];
                p.avgDistance = std::stof(parts[2]);
                p.successRate = std::stof(parts[3]);
                p.sampleCount = static_cast<uint32_t>(std::stoul(parts[4]));
                currentEntry->transferPatterns.push_back(p);
            }
        } else if (currentEntry && line.rfind("SYMMETRY:", 0) == 0) {
            std::string rest = line.substr(9);
            size_t arrow = rest.find("->");
            if (arrow != std::string::npos) {
                currentEntry->symmetryPairs.emplace_back(
                    rest.substr(0, arrow), rest.substr(arrow + 2));
            }
        } else if (currentEntry && line.rfind("SOCKET:", 0) == 0) {
            currentEntry->socketBones.push_back(line.substr(7));
        } else if (currentEntry && line.rfind("WEAPON:", 0) == 0) {
            currentEntry->weaponBones.push_back(line.substr(7));
        }
    }
    
    updateEntryStats(*currentEntry);
    return ResultVoid::ok();
}

ResultVoid SelfLearningDatabase::save(const std::filesystem::path& path) const {
    std::ofstream file(path, std::ios::binary);
    if (!file) {
        return ResultVoid::fail("Cannot write learning database: " + path.string(), "SELF_LEARN");
    }
    
    file << "# Metin2 Self-Learning Database\n";
    file << "# Generated by m2rig\n\n";
    
    for (const auto& [key, entry] : getEntries()) {
        file << "ENTRY:" << key << "\n";
        
        for (const auto& [src, tgt] : entry.boneMap) {
            float conf = entry.boneConfidence.count(src) ? entry.boneConfidence.at(src) : 1.0f;
            file << "BONEMAP:" << src << "->" << tgt << ":" << conf << "\n";
        }
        
        for (const auto& p : entry.transferPatterns) {
            file << "PATTERN:" << p.sourceBone << ":" << p.targetBone << ":"
                 << p.avgDistance << ":" << p.successRate << ":" << p.sampleCount << "\n";
        }
        
        for (const auto& [a, b] : entry.symmetryPairs) {
            file << "SYMMETRY:" << a << "->" << b << "\n";
        }
        
        for (const auto& s : entry.socketBones) {
            file << "SOCKET:" << s << "\n";
        }
        
        for (const auto& w : entry.weaponBones) {
            file << "WEAPON:" << w << "\n";
        }
        
        file << "\n";
    }
    
    return ResultVoid::ok();
}

LearningEntry* SelfLearningDatabase::getOrCreateEntry(const Gr2CharacterProfile& profile) {
    std::string key = profile.profileId.empty() 
        ? (profile.race + "_" + profile.gender + "_" + profile.variant)
        : profile.profileId;
    return getOrCreateEntryByKey(key);
}

LearningEntry* SelfLearningDatabase::getOrCreateEntryByKey(const std::string& key) {
    auto it = entries_.find(key);
    if (it == entries_.end()) {
        LearningEntry entry;
        entry.characterKey = key;
        auto [newIt, _] = entries_.emplace(key, std::move(entry));
        return &newIt->second;
    }
    return &it->second;
}

const LearningEntry* SelfLearningDatabase::getEntry(const std::string& characterKey) const {
    auto it = entries_.find(characterKey);
    return it != entries_.end() ? &it->second : nullptr;
}

void SelfLearningDatabase::recordTransfer(const Gr2CharacterProfile&,  // sourceProfile (unused, kept for API symmetry)
                                          const Gr2CharacterProfile& targetProfile,
                                          const std::string& sourceBone,
                                          const std::string& targetBone,
                                          float distance,
                                          bool success) {
    LearningEntry* entry = getOrCreateEntry(targetProfile);
    
    // Update bone map
    if (!entry->boneMap.contains(sourceBone)) {
        entry->boneMap[sourceBone] = targetBone;
        entry->boneConfidence[sourceBone] = success ? 1.0f : 0.3f;
    } else {
        // Update confidence based on success
        float& conf = entry->boneConfidence[sourceBone];
        conf = conf * 0.9f + (success ? 0.1f : -0.1f);
        conf = std::clamp(conf, 0.0f, 1.0f);
    }
    
    // Update transfer pattern
    for (auto& p : entry->transferPatterns) {
        if (p.sourceBone == sourceBone && p.targetBone == targetBone) {
            p.distanceSamples.push_back(distance);
            if (p.distanceSamples.size() > 100) p.distanceSamples.erase(p.distanceSamples.begin());
            p.avgDistance = std::accumulate(p.distanceSamples.begin(), p.distanceSamples.end(), 0.0f) 
                          / p.distanceSamples.size();
            p.successRate = p.successRate * 0.95f + (success ? 0.05f : 0.0f);
            p.sampleCount++;
            updateEntryStats(*entry);
            return;
        }
    }
    
    // New pattern
    LearningEntry::TransferPattern p;
    p.sourceBone = sourceBone;
    p.targetBone = targetBone;
    p.avgDistance = distance;
    p.successRate = success ? 1.0f : 0.0f;
    p.sampleCount = 1;
    p.distanceSamples = {distance};
    entry->transferPatterns.push_back(p);
    
    updateEntryStats(*entry);
}

void SelfLearningDatabase::recordVertexAffinities(const Gr2CharacterProfile& profile,
                                                  const Mesh& mesh,
                                                  const Skeleton& skeleton) {
    LearningEntry* entry = getOrCreateEntry(profile);
    
    // Clear old affinities
    entry->vertexAffinities.clear();
    
    // For each bone, compute vertex affinity
    for (size_t b = 0; b < skeleton.bones.size(); ++b) {
        const Bone& bone = skeleton.bones[b];
        LearningEntry::VertexAffinity affinity;
        affinity.boneName = bone.name;
        affinity.bonePosition = {bone.globalTransform.m[3][0], bone.globalTransform.m[3][1], bone.globalTransform.m[3][2]};
        
        float maxDist = 0.0f;
        for (size_t v = 0; v < mesh.vertices.size(); ++v) {
            float totalWeight = 0.0f;
            for (const auto& inf : mesh.vertices[v].influences) {
                if (inf.bone == b) {
                    totalWeight += inf.weight;
                }
            }
            if (totalWeight > 0.01f) { // Threshold for significant influence
                affinity.vertexWeights.emplace_back(static_cast<uint32_t>(v), totalWeight);
                float dist = distance(mesh.vertices[v].position, affinity.bonePosition);
                maxDist = std::max(maxDist, dist);
            }
        }
        affinity.influenceRadius = maxDist;
        if (!affinity.vertexWeights.empty()) {
            entry->vertexAffinities.push_back(std::move(affinity));
        }
    }
}

std::optional<std::string> SelfLearningDatabase::getBestMapping(const Gr2CharacterProfile&,  // sourceProfile (unused, kept for API symmetry)
                                                                const Gr2CharacterProfile& targetProfile,
                                                                const std::string& sourceBone) const {
    std::string key = targetProfile.profileId.empty() 
        ? (targetProfile.race + "_" + targetProfile.gender + "_" + targetProfile.variant)
        : targetProfile.profileId;
    const LearningEntry* entry = getEntry(key);
    if (!entry) return std::nullopt;
    
    auto it = entry->boneMap.find(sourceBone);
    if (it != entry->boneMap.end()) {
        float conf = entry->boneConfidence.count(sourceBone) ? entry->boneConfidence.at(sourceBone) : 0.5f;
        if (conf > 0.3f) return it->second;
    }
    
    // Fallback: find pattern with highest success rate
    std::optional<std::string> best;
    float bestScore = 0.0f;
    for (const auto& p : entry->transferPatterns) {
        if (p.sourceBone == sourceBone && p.successRate > bestScore) {
            bestScore = p.successRate;
            best = p.targetBone;
        }
    }
    
    return best;
}

float SelfLearningDatabase::getTransferConfidence(const Gr2CharacterProfile&,  // sourceProfile (unused)
                                                  const Gr2CharacterProfile& targetProfile,
                                                  const std::string& sourceBone,
                                                  const std::string& targetBone) const {
    std::string key = targetProfile.profileId.empty() 
        ? (targetProfile.race + "_" + targetProfile.gender + "_" + targetProfile.variant)
        : targetProfile.profileId;
    const LearningEntry* entry = getEntry(key);
    if (!entry) return 0.5f;
    
    auto it = entry->boneConfidence.find(sourceBone);
    if (it != entry->boneConfidence.end() && entry->boneMap.count(sourceBone) 
        && entry->boneMap.at(sourceBone) == targetBone) {
        return it->second;
    }
    
    // Check patterns
    for (const auto& p : entry->transferPatterns) {
        if (p.sourceBone == sourceBone && p.targetBone == targetBone) {
            return p.successRate;
        }
    }
    
    return 0.5f; // Default neutral confidence
}

const std::vector<std::pair<std::string, std::string>>& SelfLearningDatabase::getSymmetryPairs(
    const Gr2CharacterProfile& profile) const {
    static const std::vector<std::pair<std::string, std::string>> empty;
    std::string key = profile.profileId.empty() 
        ? (profile.race + "_" + profile.gender + "_" + profile.variant)
        : profile.profileId;
    const LearningEntry* entry = getEntry(key);
    return entry ? entry->symmetryPairs : empty;
}

const std::vector<std::string>& SelfLearningDatabase::getSocketBones(
    const Gr2CharacterProfile& profile) const {
    static const std::vector<std::string> empty;
    std::string key = profile.profileId.empty() 
        ? (profile.race + "_" + profile.gender + "_" + profile.variant)
        : profile.profileId;
    const LearningEntry* entry = getEntry(key);
    return entry ? entry->socketBones : empty;
}

const std::vector<std::string>& SelfLearningDatabase::getWeaponBones(
    const Gr2CharacterProfile& profile) const {
    static const std::vector<std::string> empty;
    std::string key = profile.profileId.empty() 
        ? (profile.race + "_" + profile.gender + "_" + profile.variant)
        : profile.profileId;
    const LearningEntry* entry = getEntry(key);
    return entry ? entry->weaponBones : empty;
}

void SelfLearningDatabase::updateEntryStats(LearningEntry& entry) {
    entry.totalSamples = static_cast<uint32_t>(entry.transferPatterns.size());
    entry.successfulTransfers = 0;
    for (const auto& p : entry.transferPatterns) {
        if (p.successRate > 0.5f) entry.successfulTransfers += p.sampleCount;
    }
    entry.lastUpdated = 0.0;  // Reserved (always 0): wall-clock timestamps
                              // would break deterministic .m2learn round-trips; the field is
                              // never read, kept for format compatibility.
}

void SelfLearningDatabase::printStats() const {
    std::cout << "=== Self-Learning Database Stats ===\n";
    std::cout << "Entries: " << entries_.size() << "\n";
    for (const auto& [key, entry] : entries_) {
        std::cout << "  [" << key << "] samples=" << entry.totalSamples 
                  << " successful=" << entry.successfulTransfers
                  << " patterns=" << entry.transferPatterns.size()
                  << " affinities=" << entry.vertexAffinities.size() << "\n";
    }
}

// --- SelfLearningTransfer implementation ---

SelfLearningTransfer::SelfLearningTransfer(SelfLearningDatabase& db) : db_(db) {}

Result<WeightTransferStats> SelfLearningTransfer::transfer(
    SelfLearningDatabase& db,
    const Mesh& sourceMesh,
    const Skeleton& sourceSkeleton,
    const Gr2CharacterProfile& sourceProfile,
    Mesh& targetMesh,
    Skeleton& targetSkeleton,
    const Gr2CharacterProfile& targetProfile,
    uint32_t kNearest,
    const std::set<uint32_t>* lockedBones) {
    
    WeightTransferStats stats;
    stats.verticesProcessed = 0;
    stats.verticesMapped = 0;
    stats.verticesUnmapped = 0;
    stats.avgDistance = 0.0;
    stats.removedMass = 0.0;
    
    // Build bone mapping using learned patterns
    std::vector<int> boneMap(targetSkeleton.bones.size(), -1);
    for (size_t t = 0; t < targetSkeleton.bones.size(); ++t) {
        const std::string& targetBone = targetSkeleton.bones[t].name;
        // Find source bone that maps to this target
        for (size_t s = 0; s < sourceSkeleton.bones.size(); ++s) {
            const std::string& sourceBone = sourceSkeleton.bones[s].name;
            auto mapping = db.getBestMapping(sourceProfile, targetProfile, sourceBone);
            if (mapping && *mapping == targetBone) {
                boneMap[t] = static_cast<int>(s);
                break;
            }
        }
        // Fallback: exact name match
        if (boneMap[t] == -1) {
            for (size_t s = 0; s < sourceSkeleton.bones.size(); ++s) {
                if (sourceSkeleton.bones[s].name == targetBone) {
                    boneMap[t] = static_cast<int>(s);
                    break;
                }
            }
        }
    }
    
    // Transfer weights using kNN with learned affinities
    double totalDist = 0.0;
    for (size_t v = 0; v < targetMesh.vertices.size(); ++v) {
        stats.verticesProcessed++;
        const Vec3& vertPos = targetMesh.vertices[v].position;
        
        // Find k nearest bones using learned patterns
        auto nearest = findNearestBonesLearned(vertPos, targetSkeleton, targetProfile, kNearest);
        if (nearest.empty()) {
            stats.verticesUnmapped++;
            continue;
        }
        
        // Apply learned affinities if available
        applyLearnedAffinities(targetMesh, targetSkeleton, targetProfile);
        
        // Standard kNN transfer
        std::vector<BoneInfluence> newInfluences;
        float totalWeight = 0.0f;
        
        for (const auto& [boneIdx, dist] : nearest) {
            if (lockedBones && lockedBones->count(boneIdx)) continue;
            if (boneMap[boneIdx] == -1) continue;
            
            size_t srcBoneIdx = static_cast<size_t>(boneMap[boneIdx]);
            
            // Find corresponding vertex in source (simplified: nearest by position)
            float bestDist = std::numeric_limits<float>::max();
            size_t bestSrcVert = 0;
            for (size_t sv = 0; sv < sourceMesh.vertices.size(); ++sv) {
                float d = distance(vertPos, sourceMesh.vertices[sv].position);
                if (d < bestDist) {
                    bestDist = d;
                    bestSrcVert = sv;
                }
            }
            
            // Get weight from source vertex for mapped bone
            for (const auto& inf : sourceMesh.vertices[bestSrcVert].influences) {
                if (inf.bone == srcBoneIdx) {
                    float w = inf.weight * (1.0f / (1.0f + dist * 10.0f)); // Distance falloff
                    newInfluences.push_back({static_cast<uint32_t>(boneIdx), w});
                    totalWeight += w;
                    totalDist += dist;
                    break;
                }
            }
        }
        
        // Normalize and clamp to 4 influences
        if (!newInfluences.empty()) {
            std::sort(newInfluences.begin(), newInfluences.end(),
                     [](const BoneInfluence& a, const BoneInfluence& b) {
                         return a.weight > b.weight;
                     });
            
            if (newInfluences.size() > 4) {
                float excess = 0.0f;
                for (size_t i = 4; i < newInfluences.size(); ++i) {
                    excess += newInfluences[i].weight;
                }
                stats.removedMass += excess;
                newInfluences.resize(4);
            }
            
            // Renormalize
            float sum = 0.0f;
            for (auto& inf : newInfluences) sum += inf.weight;
            if (sum > 0.0f) {
                for (auto& inf : newInfluences) inf.weight /= sum;
            }
            
            targetMesh.vertices[v].influences = std::move(newInfluences);
            stats.verticesMapped++;
        } else {
            stats.verticesUnmapped++;
        }
    }
    
    if (stats.verticesMapped > 0) {
        stats.avgDistance = totalDist / stats.verticesMapped;
    }
    
    return Result<WeightTransferStats>::ok(stats);
}

Result<AutoRigStats> SelfLearningTransfer::autoRig(
    SelfLearningDatabase&,  // db (unused, uses db_ member)
    Mesh& mesh,
    Skeleton& skeleton,
    const Gr2CharacterProfile& profile,
    float maxDistance,
    const std::set<uint32_t>* lockedBones) {
    
    AutoRigStats stats;
    stats.verticesBound = 0;
    stats.avgDistance = 0.0;
    stats.maxDistance = 0.0;
    stats.removedMass = 0.0;
    
    // Apply learned vertex affinities
    applyLearnedAffinities(mesh, skeleton, profile);
    
    // For vertices without learned affinities, use distance-based assignment
    double totalDist = 0.0;
    for (size_t v = 0; v < mesh.vertices.size(); ++v) {
        if (!mesh.vertices[v].influences.empty()) {
            stats.verticesBound++;
            continue;
        }
        
        const Vec3& vertPos = mesh.vertices[v].position;
        auto nearest = findNearestBonesLearned(vertPos, skeleton, profile, 4);
        
        std::vector<BoneInfluence> influences;
        float totalDistV = 0.0f;
        
        for (const auto& [boneIdx, dist] : nearest) {
            if (lockedBones && lockedBones->count(boneIdx)) continue;
            if (dist > maxDistance) continue;
            
            float weight = 1.0f / (1.0f + dist * 20.0f);
            influences.push_back({static_cast<uint32_t>(boneIdx), weight});
            totalDistV += dist;
        }
        
        if (!influences.empty()) {
            // Normalize
            float sum = 0.0f;
            for (auto& inf : influences) sum += inf.weight;
            if (sum > 0.0f) {
                for (auto& inf : influences) inf.weight /= sum;
            }
            
            // Clamp to 4
            if (influences.size() > 4) influences.resize(4);
            
            mesh.vertices[v].influences = std::move(influences);
            stats.verticesBound++;
            double avgDistV = totalDistV / influences.size();
            totalDist += avgDistV;
            stats.maxDistance = std::max(stats.maxDistance, avgDistV);
        }
    }
    
    if (stats.verticesBound > 0) {
        stats.avgDistance = totalDist / stats.verticesBound;
    }
    
    // Count bones used
    std::set<uint32_t> usedBones;
    for (const auto& v : mesh.vertices) {
        for (const auto& inf : v.influences) {
            usedBones.insert(inf.bone);
        }
    }
    
    return Result<AutoRigStats>::ok(stats);
}

std::vector<std::pair<uint32_t, float>> SelfLearningTransfer::findNearestBonesLearned(
    const Vec3& vertexPos,
    const Skeleton& skeleton,
    const Gr2CharacterProfile& profile,
    uint32_t k) const {
    
    std::string key = profile.profileId.empty() 
        ? (profile.race + "_" + profile.gender + "_" + profile.variant)
        : profile.profileId;
    const LearningEntry* entry = db_.getEntry(key);
    
    std::vector<std::pair<uint32_t, float>> candidates;
    candidates.reserve(skeleton.bones.size());
    
    for (size_t b = 0; b < skeleton.bones.size(); ++b) {
        const Bone& bone = skeleton.bones[b];
        Vec3 bonePos{bone.globalTransform.m[3][0], bone.globalTransform.m[3][1], bone.globalTransform.m[3][2]};
        float dist = distance(vertexPos, bonePos);
        
        // Boost confidence if bone has learned affinity
        float confidence = 1.0f;
        if (entry) {
            for (const auto& aff : entry->vertexAffinities) {
                if (aff.boneName == bone.name) {
                    confidence = 1.0f + aff.influenceRadius * 0.1f; // Boost for learned bones
                    dist *= 0.8f; // Reduce effective distance
                    break;
                }
            }
        }
        
        candidates.emplace_back(static_cast<uint32_t>(b), dist / confidence);
    }
    
    std::partial_sort(candidates.begin(), 
                     candidates.begin() + std::min(k, static_cast<uint32_t>(candidates.size())),
                     candidates.end(),
                     [](const auto& a, const auto& b) { return a.second < b.second; });
    
    candidates.resize(std::min(k, static_cast<uint32_t>(candidates.size())));
    return candidates;
}

void SelfLearningTransfer::applyLearnedAffinities(
    Mesh& mesh,
    const Skeleton& skeleton,
    const Gr2CharacterProfile& profile) const {
    
    std::string key = profile.profileId.empty() 
        ? (profile.race + "_" + profile.gender + "_" + profile.variant)
        : profile.profileId;
    const LearningEntry* entry = db_.getEntry(key);
    if (!entry) return;
    
    // Build bone name to index map
    std::unordered_map<std::string, uint32_t> boneIndex;
    for (size_t i = 0; i < skeleton.bones.size(); ++i) {
        boneIndex[skeleton.bones[i].name] = static_cast<uint32_t>(i);
    }
    
    for (const auto& affinity : entry->vertexAffinities) {
        auto it = boneIndex.find(affinity.boneName);
        if (it == boneIndex.end()) continue;
        
        uint32_t boneIdx = it->second;
        
        for (const auto& [vertIdx, weight] : affinity.vertexWeights) {
            if (vertIdx >= mesh.vertices.size()) continue;
            
            // Add or update influence
            auto& influences = mesh.vertices[vertIdx].influences;
            bool found = false;
            for (auto& inf : influences) {
                if (inf.bone == boneIdx) {
                    inf.weight = std::max(inf.weight, weight);
                    found = true;
                    break;
                }
            }
            if (!found) {
                influences.push_back({boneIdx, weight});
            }
        }
    }
}

// --- Gr2BatchAnalyzer implementation ---

Gr2BatchAnalyzer::Gr2BatchAnalyzer(SelfLearningDatabase& db) : db_(db) {}

ResultVoid Gr2BatchAnalyzer::analyzeDirectory(const std::filesystem::path& dirPath) {
    if (!std::filesystem::exists(dirPath)) {
        return ResultVoid::fail("Directory does not exist: " + dirPath.string(), "GR2_ANALYZE");
    }
    
    results_.clear();
    
    for (const auto& entry : std::filesystem::recursive_directory_iterator(dirPath)) {
        if (entry.is_regular_file() && entry.path().extension() == ".gr2") {
            processGr2File(entry.path());
        }
    }
    
    return ResultVoid::ok();
}

ResultVoid Gr2BatchAnalyzer::analyzeBonesPresets(const std::filesystem::path& bonesDir) {
    // Analyze SMD/FBX files exported from 00-BONES 3ds Max presets
    if (!std::filesystem::exists(bonesDir)) {
        return ResultVoid::fail("Bones directory does not exist: " + bonesDir.string(), "GR2_ANALYZE");
    }
    
    for (const auto& entry : std::filesystem::recursive_directory_iterator(bonesDir)) {
        if (entry.is_regular_file()) {
            std::string ext = entry.path().extension().string();
            std::transform(ext.begin(), ext.end(), ext.begin(),
               [](unsigned char c) { return static_cast<char>(std::tolower(c)); });
            if (ext == ".smd" || ext == ".fbx") {
                // Could parse and analyze these too
            }
        }
    }
    
    return ResultVoid::ok();
}

ResultVoid Gr2BatchAnalyzer::buildInitialDatabase() {
    for (const auto& result : results_) {
        if (!result.success) continue;
        
        LearningEntry* entry = db_.getOrCreateEntry(result.profile);
        
        // Extract bone hierarchy
        extractBoneHierarchy(result.parseResult, *entry);
        
        // Extract vertex affinities from mesh
        if (result.parseResult.hasMesh && !result.parseResult.meshes.empty()) {
            // Convert first mesh and skeleton to m2rig format
            auto skel = parser_.toSkeleton(result.parseResult);
            auto mesh = parser_.toMesh(result.parseResult, 0);
            if (skel && mesh) {
                extractVertexAffinities(result.parseResult, *entry);
                detectSymmetryPairs(result.parseResult, *entry);
            }
        }
    }
    
    return ResultVoid::ok();
}

ResultVoid Gr2BatchAnalyzer::exportReport(const std::filesystem::path& outputPath) const {
    std::ofstream file(outputPath);
    if (!file) {
        return ResultVoid::fail("Cannot write report: " + outputPath.string(), "GR2_ANALYZE");
    }
    
    file << "# GR2 Batch Analysis Report\n";
    file << "# Files analyzed: " << results_.size() << "\n\n";
    
    for (const auto& r : results_) {
        file << "## " << r.filename << "\n";
        file << "  Profile: " << r.profile.profileId << " (" << r.profile.race << "/" << r.profile.gender << ")\n";
        file << "  Success: " << (r.success ? "YES" : "NO") << "\n";
        if (!r.success) {
            file << "  Error: " << r.error << "\n";
        } else {
            file << "  Bones: " << r.parseResult.bones.size() << "\n";
            file << "  Meshes: " << r.parseResult.meshes.size() << "\n";
            file << "  Has Weights: " << (r.parseResult.hasWeights ? "YES" : "NO") << "\n";
            file << "  Has Animation: " << (r.parseResult.hasAnimation ? "YES" : "NO") << "\n";
        }
        file << "\n";
    }
    
    return ResultVoid::ok();
}

void Gr2BatchAnalyzer::processGr2File(const std::filesystem::path& filePath) {
    AnalysisResult result;
    result.filename = filePath.filename().string();
    
    auto parseResult = parser_.parse(filePath.string());
    if (!parseResult) {
        result.success = false;
        result.error = parseResult.error().message;
        results_.push_back(std::move(result));
        return;
    }
    
    result.parseResult = std::move(parseResult.value());
    result.profile = detectGr2Character(result.filename, result.parseResult);
    result.success = true;
    results_.push_back(std::move(result));
}

void Gr2BatchAnalyzer::extractBoneHierarchy(const Gr2ParseResult& result, LearningEntry& entry) {
    entry.socketBones.clear();
    entry.weaponBones.clear();
    
    for (const auto& bone : result.bones) {
        if (bone.isSocket) entry.socketBones.push_back(bone.name);
        if (bone.isWeapon) entry.weaponBones.push_back(bone.name);
    }
}

void Gr2BatchAnalyzer::extractVertexAffinities(const Gr2ParseResult& result, LearningEntry& entry) {
    // Extract basic bone position info
    for (const auto& bone : result.bones) {
        LearningEntry::VertexAffinity affinity;
        affinity.boneName = bone.name;
        affinity.bonePosition = bone.position;
        affinity.influenceRadius = bone.length;
        entry.vertexAffinities.push_back(std::move(affinity));
    }
}

void Gr2BatchAnalyzer::detectSymmetryPairs(const Gr2ParseResult& result, LearningEntry& entry) {
    entry.symmetryPairs.clear();
    
    // Common Metin2 symmetry patterns
    std::unordered_map<std::string, std::string> leftToRight = {
        {"L_", "R_"}, {"Left", "Right"}, {"_L", "_R"}, {"_l", "_r"},
        {"l_", "r_"}, {"left_", "right_"}
    };
    
    std::set<std::string> boneNames;
    for (const auto& bone : result.bones) {
        boneNames.insert(bone.name);
    }
    
    for (const auto& name : boneNames) {
        for (const auto& [left, right] : leftToRight) {
            if (name.rfind(left, 0) == 0) { // starts with left prefix
                std::string rightName = right + name.substr(left.size());
                if (boneNames.count(rightName)) {
                    entry.symmetryPairs.emplace_back(name, rightName);
                }
            } else if (name.size() >= left.size() && 
                       name.compare(name.size() - left.size(), left.size(), left) == 0) { // ends with left suffix
                std::string rightName = name.substr(0, name.size() - left.size()) + right;
                if (boneNames.count(rightName)) {
                    entry.symmetryPairs.emplace_back(name, rightName);
                }
            }
        }
    }
}

}  // namespace m2rig